In [1]:
import numpy as np
import pandas as pd

## ndarray

### array의 생성

In [5]:
test_array = np.array(["1", 3, 4, 6], float) # String, int 데이터를 float으로
test_array

array([1., 3., 4., 6.])

In [4]:
type(test_array[3]) # array 생성시 자동 형변환

numpy.float64

In [6]:
type(test_array[0])

numpy.float64

In [7]:
test_array.dtype #Array 전체 데이터 Type을 반환한다.

dtype('float64')

### Array .shape

In [9]:
test_array.shape #Array 의 크기(길이)를 반환한다. type : tuple

(4,)

In [10]:
matrix = [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]
np.array(matrix, int).shape

(3, 4)

In [11]:
tensor = [[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]],
          [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]],
          [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]],
          [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]]

np.array(tensor, int).shape

(4, 3, 4)

In [12]:
# ndim - number of dimension
np.array(tensor, int).shape

(4, 3, 4)

In [13]:
# size - number o data
np.array(tensor, int).size

48

### Shape handling

In [14]:
#reshape : 크기를 변경, 갯수는 동일
test_matrix = [[1, 2, 3, 4], [3, 4, 5, 6]]
np.array(test_matrix).shape

(2, 4)

In [16]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 3, 4, 5, 6])

In [17]:
np.array(test_matrix).reshape(2, 4).shape

(2, 4)

In [20]:
# -1 인자 : Element의 개수, size에 따라 row의 개수 선정
np.array(test_matrix).reshape(-1, 2).shape

(4, 2)

In [22]:
np.array(test_matrix).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[3, 4],
        [5, 6]]])

In [23]:
np.array(test_matrix).reshape(2, -1)

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [24]:
#flatten : 1차원으로 만들어줌
test_flatten = [[1,2,3,4], [1,2,3,5], [1,2,3,4], [5,6,3,8]]
np.array(test_flatten).flatten()

array([1, 2, 3, 4, 1, 2, 3, 5, 1, 2, 3, 4, 5, 6, 3, 8])

### Indexing & Slicing

In [27]:
#indexing
a = np.array([[1,2,3],[4.5, 5, 6]], int)

print(a)
print(a[0, 0]) #[row, column]
print(a[0][0])

# 할당
a[0,0] = 12
print(a)
a[0,0] = 13
print(a)

[[1 2 3]
 [4 5 6]]
1
1
[[12  2  3]
 [ 4  5  6]]
[[13  2  3]
 [ 4  5  6]]


In [28]:
# slicing
# 행과 열을 나눠서 Slicing 가능하다.
a = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)

In [29]:
a[:, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [30]:
a[1, 1:3]

array([7, 8])

In [31]:
a[1:3]

array([[ 6,  7,  8,  9, 10]])

In [32]:
a[:,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

### arange

In [37]:
# List의 range 같은 효과, 0 ~ 29까지 숫자를 배열로 추출
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
np.arange(30).reshape(-1, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [39]:
np.arange(0, 5, 0.5) # (시작, 끝, step), floating point도 표시 가능, list는 안됌

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### ones, zeros & empty

In [40]:
# ~로 가득찬 ndarraya생성 가능

In [41]:
# 0으로 가득찬
np.zeros(shape = (10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [42]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
# 1로 가득찬
np.ones(shape = (10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [45]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
# shape 만 주어지고 비어있는 ndarray 생성, 메모리 초기화가 되어있지 않음
np.empty(shape = (10, ), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [47]:
np.empty((3, 5))

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

In [49]:
#something_like : ndarray의 shape만큼 1, 0 또는 empty array를 반환한다.
test_matrix  = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

### identity

In [50]:
# 단위 행렬을 생성
np.identity(n=3, dtype= np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [51]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### eye

In [53]:
# 대각선이 1인 행렬, k 값을 조절하여 starting point 변경 가능
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [54]:
# same as identity
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
# k -> start index
np.eye(3, 5, k = 2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### diag

In [56]:
# 대각 행렬의 값을 추출
matrix = np.arange(9).reshape(3, 3)
np.diag(matrix)

array([0, 4, 8])

In [57]:
# k로 start index 조절가능
np.diag(matrix, k=1)

array([1, 5])

### random sampling

In [58]:
# 데이터 분포에 따른 sampling array를 생성

In [59]:
# 균등분포
np.random.uniform(0, 1, 10).reshape(2, 5)

array([[0.77223834, 0.03180312, 0.96743473, 0.06703168, 0.86925909],
       [0.42070001, 0.55039957, 0.13598279, 0.90441418, 0.70016302]])

In [61]:
# 정규분포 (평균, 표준편차, 데이터 개수)
np.random.normal(0, 1, 10).reshape(2, 5)

array([[ 0.07783175, -2.71534594, -0.5985235 ,  0.66889967, -0.42237235],
       [-1.44309355,  0.07782997,  0.35230488,  1.18316584,  0.1430112 ]])

### Operational Function

In [62]:
#sum
test_array = np.arange(1, 11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
test_array.sum(dtype=np.float)

55.0

In [66]:
#axis : 모든 operation function을 실행할 때, 기준이 되는 dimension 축
# 차원이 높아지면서 추가되는 축을 0으로 한다.
test_array = np.arange(1, 13).reshape(3, 4)
test_array


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
test_array.sum(axis = 1) # 각 row의 합

array([10, 26, 42])

In [70]:
test_array.sum(axis = 0) # 각 column의 합

array([15, 18, 21, 24])

In [74]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [75]:
third_order_tensor.sum(axis = 0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [76]:
third_order_tensor.sum(axis = 1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [77]:
third_order_tensor.sum(axis = 2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

### mean & std

In [80]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
# 평균
test_array.mean()

6.5

In [82]:
test_array.mean(axis = 0)

array([5., 6., 7., 8.])

In [85]:
# 표준편차
test_array.std()

3.452052529534663

In [86]:
test_array.std(axis = 0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

### concatenate

In [87]:
# .vstack -> 수직적으로 결합
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [90]:
# .hstack -> 수평적으로 결합
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])

np.hstack((a, b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [91]:
# Contatenate with axis로 .hstack, .vstack과 똑같은 기능을 수행할 수 있다.
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.concatenate((a,b), axis = 0)

array([1, 2, 3, 2, 3, 4])

In [97]:
# .T : transpose 행과 열 바꾸기
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

### array operations

- Numpy는 array간 기본적인 사칙 연산을 지원한다.

In [98]:
test_a = np.array([[1, 2, 3], [4, 5, 6]])
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
test_a + test_a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [100]:
test_a - test_a

array([[0, 0, 0],
       [0, 0, 0]])

In [102]:
# Matrix내 같은 위치에 있는 값들끼리 연산 -> Element-wise operations
# Array간 shape이 같을 때 일어나는 연산
test_a * test_a

array([[ 1,  4,  9],
       [16, 25, 36]])

### Dot product
- matrix 기본연산
- .dot 함수 사용

In [104]:
test_a = np.arange(1, 7).reshape(2, 3)
test_b = np.arange(7, 13).reshape(3, 2)

test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

### Transpose

In [105]:
test_a = np.arange(1, 7).reshape(2, 3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
test_b = test_a.transpose()
# same as test_a.T

In [111]:
test_b.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

### BroadCasting
- shape이 다른 배열간 연산을 지원하는 기능
- Scalar-vector 외에도 vector-matrix 간의 연산도 지원
- 행과 행간의 크기나, 열과 열간의 크기가 맞아야 실행

In [118]:
test_matrix = np.arange(1, 7).reshape(2, 3)
test_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
scalar = 3

In [120]:
test_matrix - 3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [121]:
test_matrix + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [122]:
test_matrix * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [123]:
mat = np.arange(1, 13).reshape(4, 3)
vec = np.arange(10, 40, 10)
mat + vec

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

### All & Any
- Array내 데이터 전부 또는 일부가 조건에 만족하면 반환

In [124]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
# 하나라도 만족하면 true
np.any(a>5)

True

In [127]:
np.any(a < 0)

False

In [126]:
# 모두 만족하면 true
np.all(a> 5)

False

In [128]:
np.all(a < 10)

True

In [131]:
# 아래의 조건에대해 array내 각 요소의 결과를 보여준다.
a < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

### Comparison Operation

In [134]:
# 비교 배열의 크기가 같을 때
test_a = np.array([1, 3, 0], float)
test_b = np.array([2, 1, 5], float)
test_a < test_b

array([ True, False,  True])

In [135]:
test_a == test_b

array([False, False, False])

In [136]:
(test_a > test_b).any()

True

In [137]:
# .logical_and, .logical_not, .logical_or
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [138]:
b = np.array([True, True, False], bool)
np.logical_not(b)

array([False, False,  True])

In [140]:
c = np.array([False, False, False], bool)
np.logical_or(b, c)

array([ True,  True, False])

### np.where

In [141]:
# is same as If statesment
np.where(a> 0, 3, 2)

array([3, 3, 2])

In [145]:
# true인 값을 뽑아주는 것이 아니라, true인 값의 위치(index) 출력한다.
a = np.arange(10)
np.where(a > 5)

(array([6, 7, 8, 9]),)

In [146]:
# .isnan -> nan 인지아닌지
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [147]:
# 한정된 값에 대해 return True
np.isfinite(a)

array([ True, False, False])

### argmax & argmin
- Array내 최대값 또는 최소값의 index를 반환

In [148]:
a = np.array([1 ,2, 4, 5, 32, 56, 34])
a.argmax()

5

In [149]:
a.argmin()

0

In [151]:
#axis 기반의 반환
a = np.array([[1, 2, 4, 7], [9, 88, 6, 45], [9, 76, 3, 4]])
np.argmax(a, axis = 1), np.argmin(a, axis = 0)

(array([3, 1, 1]), array([0, 0, 2, 2]))

### Boolean index
- 특정 조건에 따른 값을 배열 형태로 추출 가능
- Comparison operation 함수들도 모두 사용가능

In [153]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [154]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [155]:
condition = test_array > 5 #boolean numpy list
test_array[condition]

array([8., 9., 7.])

In [156]:
# .astype(np.int) -> True, False의 값을 특정 타입으로 바꿈

### Fancy index
- numpy는 index를 index value로 사용해서 값을 추출하는 방법

In [158]:
# index 범위를 벗어난 값이 등장하면 error가 나온다
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

array([2., 2., 4., 8., 6., 4.])

In [159]:
# 더 자주 씀
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [161]:
# Fancy index in matrix
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

### Numpy File I/O

In [ ]:
# load file
a = np.loadtxt("./populations.txt")
# dtype 인자를 통해 데이터 타입을 설정 가능하다
a[:10]

In [ ]:
a_int = a.astype(int)
a_int[:3]

In [ ]:
np.savetxt("int_data.csv", a_int, delimeter=',')
# fmt 인자를 추가해 데이터 저장 포멧을 설정할 수 있다. -> %d

### numpy object - npy
- Numpy object(pickle)형태로 데이터를 저장하고 불러옴

In [ ]:
# File out
np.save("npy_test", arr=a_int)

In [ ]:
npy_array = np.load(file="npy_test.npy")
npy_array[:3]